# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-14 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_title', models.CharField(max_length=20)),
                ('mood_time', models.CharField(max_length=20)),
                ('mood_content', models.CharField(default='开心的很，没有要讲的', max_length=128)),
            ],
        ),
    ]
